from arxiv_classification import Classification, get_computer_science_category_list


def test_get_computer_science_category_list():
    assert get_computer_science_category_list() == [
             Classification('cs.AI'),
             Classification('cs.AR'),
             Classification('cs.CC'),
             Classification('cs.CE'),
             Classification('cs.CG'),
             Classification('cs.CL'),
             Classification('cs.CR'),
             Classification('cs.CV'),
             Classification('cs.CY'),
             Classification('cs.DB'),
             Classification('cs.DC'),
             Classification('cs.DL'),
             Classification('cs.DM'),
             Classification('cs.DS'),
             Classification('cs.ET'),
             Classification('cs.FL'),
             Classification('cs.GL'),
             Classification('cs.GR'),
             Classification('cs.GT'),
             Classification('cs.HC'),
             Classification('cs.IR'),
             Classification('cs.IT'),
             Classification('cs.LG'),
             Classification('cs.LO'),
             Classification('cs.MA'),
             Classification('cs.MM'),
             Classification('cs.MS'),
             Classification('cs.NA'),
             Classification('cs.NE'),
             Classification('cs.NI'),
             Classification('cs.OH'),
             Classification('cs.OS'),
             Classification('cs.PF'),
             Classification('cs.PL'),
             Classification('cs.RO'),
             Classification('cs.SC'),
             Classification('cs.SD'),
             Classification('cs.SE'),
             Classification('cs.SI'),
             Classification('cs.SY')
        ]
